name: Rebase Open PRs on Merge
on:
  push:
    branches:
      - main
jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy" 
          git config user.email "vishnu4reddy" 

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Get list of open PRs
        id: pr_list
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "::set-output name=prs::$prs"

      - name: Rebase each open PR
        run: |
          for pr in $(echo "${{ steps.pr_list.outputs.prs }}" | tr " " "\n")
          do
            pr_number=$(echo $pr | awk '{print $1}')
            pr_branch=$(echo $pr | awk '{print $2}')

            echo "Rebasing PR #$pr_number ($pr_branch)"

            # Fetch the base branch (main)
            git fetch origin main

            # Checkout the PR branch
            git checkout $pr_branch

            # Check if the PR is already up-to-date with the base branch (main)
            if git merge-base --is-ancestor origin/main HEAD; then
              echo "PR #$pr_number is already up-to-date with main, skipping rebase."
            else
              # Rebase onto the latest main branch
              git rebase origin/main

              # Push the rebased branch (force-push safely)
              git push origin $pr_branch --force-with-lease
            fi
          done
    env:
      GH_TOKEN: ${{ github.token }}
